### ISSUE TITLE
Method is Not Showing in GUI after running the java mujava.gui.RunTestMain commad

### ISSUE THREAD

**Issue by younas-bangash** [jeffoffutt/muJava#4]
When i create the mutant methods show in that GUI properly but when I try to run the command java mujava.gui.RunTestMain and new GUI open but in that GUI methods is not displaying

**Comment by dmark1021** [comment]
Can you provide some screenshots?

**Comment by younas-bangash** [comment]
![catpture2](https://cloud.githubusercontent.com/assets/4440531/20843661/a25612d8-b8d5-11e6-98f4-4c964dc94ff0.PNG)
No Method is displaying while when i move to the Mutants Viewer it shows the methods

**Comment by dmark1021** [comment]
try clicking the class dropbox and pick a class first?

**Comment by younas-bangash** [comment]
Thanks it work but mutant score is 0% i am working on vendingmachine which is given on the website [](https://cs.gmu.edu/~offutt/mujava/)

**Comment by dmark1021** [comment]
Yes, try selecting it again to trigger the event handler?

**Comment by younas-bangash** [comment]
![mutant score](https://cloud.githubusercontent.com/assets/4440531/20846749/813f57bc-b8e4-11e6-902d-acd1e8d19477.PNG)
As from the figure which is shown above I select the class and run for 3 sec all the mutant are live and why the mutant score is 0.0% ?

**Comment by dmark1021** [comment]
Yes, all the mutants are live, so the mutation score is 0.
Please design some tests that kill at least some mutants.

**Comment by jeffoffutt** [comment]
Lin,
This is a bit ridiculous. You don't need to answer any more questions. We do not have the resources to operate a basic helpdesk.

Jeff Offutt
Sent from a pocket computer
Pardon brevity and any odd spell corrections

On Dec 2, 2016, at 6:33 PM, Lin Deng <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, all the mutants are live, so the mutation score is 0.
Please design some tests that kill at least some mutants.

-

**Comment by younas-bangash** [comment]
@dmark1021 I run the same code on MuClipse and it is killing some mutants but mujava is not. @jeffoffutt I search for basic help but i did not find so that's why i come here If you can't help than i will close the issue

**Comment by jeffoffutt** [comment]
I did not realize my previous reply went to everyone, or I might have 
been more polite. But the point remains.

We do not have any funding for muJava. If it's broken in some way, we 
will try to donate our own personal time to fix it, but we don't have 
the resources (time or money) to help with basic usage questions. Lin is 
trying to complete his PhD and is unfortunately behind where he should be.

Sorry we cannot supply more support, but this is not a commercial or 
money-making tool. Thank you for understanding.

Sincerely,

~Jeff Offutt


-- 
Jeff Offutt, PhD
Professor of Software Engineering
Director, MS Software Engineering
MS 4A5, George Mason University
Fairfax, VA  22030-4444 USA
offutt@gmu.edu
www.cs.gmu.edu/~offutt
